apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NadaBargougui/Kubernetes-observability-project/Kubernetes/sockshop/kustomize
    targetRevision: HEAD
    path: Kubernetes/sockshop/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
      prune: true
