apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sockshop-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true" # if your Ingress paths include (/|$)(.*)
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /front-end(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: front-end.sockshop.svc.cluster.local
                namespace: sockshop
                port:
                  number: 80
